
- name: Package Armvirt as OpenWrt
  uses: unifreq/openwrt_packit@master
  env:
    OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*rootfs.tar.gz
    PACKAGE_SOC: s905d_s905x3_s922x_vplus_beikeyun_l1pro_qemu
    KERNEL_VERSION_NAME: 5.15.35_5.17.5
