
- name: Package Armvirt as OpenWrt
  uses: unifreq/openwrt_packit@master
  env:
    OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*rootfs.tar.gz
    PACKAGE_SOC: s905d
    KERNEL_VERSION_NAME: 5.15.74
    
    - name: Upload OpenWrt Firmware to Release
  uses: ncipollo/release-action@main
  with:
    tag: openwrt_armvirt_v8_${{ env.PACKAGED_OUTPUTDATE }}
    artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
    allowUpdates: true
    token: ${{ secrets.GH_TOKEN }}
    body: |
      This is OpenWrt firmware for Armvirt 64
      * Firmware information
      Default IP: 192.168.2.1
      Default username: root
      Default password: password
